let enames=["aryan","peera vali","syed","aryan","azma" ]
console.log(enames)
enames.push("ayyat")
console.log(enames)
enames.pop()
console.log(enames)
enames.shift()
console.log(enames)
enames.unshift("ayyat")
console.log(enames)